spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/monew
    username: monew
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none #'update'로 처음 실행 후 'none'으로 변경
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: debug