spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/monew
    username: monew
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update #'update'로 처음 실행 후 'none'으로 변경
    show-sql: true
    open-in-view: false