spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/monew
    username: monew
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update  # 또는 create, create-drop (처음 실행 시)
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/monew

add:
  db-type: mongodb

log:
  file:
    path: ./logs-dev