spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: monew
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver

logging:
  level:
    root: info

admin:
  email: admin@example.com
  password: supersecret
  nickname: admin

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  endpoint:
    health:
      show-details: always

monew:
  storage:
    s3:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
      region: ${AWS_S3_REGION}
      bucket: ${AWS_S3_BUCKET}
      presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600}