spring:
  application:
    name: monew
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver

logging:
  level:
    root: info

admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}
  nickname: admin